# Generated by Django 6.0.5 on 2026-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
