# Generated by Django 6.0.5 on 2026-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente de Soporte'), ('admin', 'Administrador'), ('superUser', 'Super Usuario')], default='cliente', max_length=20),
        ),
    ]
