# Generated by Django 6.0.5 on 2026-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_imagen_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='para',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
