# Generated by Django 6.0.5 on 2026-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='grupo',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('sistema', 'Sistema')], default='tecnologia', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('incidencia', 'Incidencia'), ('requerimiento', 'Requerimiento')], default='incidencia', max_length=20),
        ),
    ]
