# Generated by Django 6.0.5 on 2026-08-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_grupo_ticket_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaTicket',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('es_nota_interna', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mencionados', models.ManyToManyField(blank=True, related_name='menciones', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tickets.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respuesta_ticket',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
