# Generated by Django 6.0.5 on 2026-08-13 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_respuestaticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketd_colaborados', to=settings.AUTH_USER_MODEL),
        ),
    ]
